### ISSUE TITLE
Use keyword hierarchy for custom reported events

### ISSUE THREAD

**Issue by caioaao** [caioaao/kaocha-greenlight#1]
@plexus said:

>  Instead the recommended thing to do is to emit custom event types, but to use Kaocha's keyword hierarchy to map them to things Kaocha knows about. To get custom formatting of errors/failures you can extend `kaocha.report/fail-summary` and `kaocha.report/print-expr`

**Comment by robhanlon22** [comment]
Extension of the `clojure.test/report` multimethod was removed in #13, instead opting to just use greenlight's built-in event print handler to keep everything in sync,
