### ISSUE TITLE
Publish new version or grant me access to Clojars artifact?

### ISSUE THREAD

**Issue by robhanlon22** [caioaao/kaocha-greenlight#12]
Thank you in advance, would also be nice to have CI access as well!

**Comment by robhanlon22** [comment]
Oh—you did grant me access to CI I think! Thank you

**Comment by robhanlon22** [comment]
It appears that the CircleCI GitHub deploy key has expired.

**Comment by robhanlon22** [comment]
@caioaao ping—can you help here?

**Comment by caioaao** [comment]
done! recreated the deploy key
