### ISSUE TITLE
Example from greenlight README not working

### ISSUE THREAD

**Issue by orestis** [caioaao/kaocha-greenlight#5]
Hello, thanks for taking the time for releasing this. I saw a recent blog post of greenlight and it looked very promising, and then since I'm using Kaocha, I thought I'd give this library a try too.

Unfortunately trying to just follow the greenlight README, it seems like Kaocha doesn't pickup the tests correctly -- some simple cases are picked up, but the more complex case of inputs/outputs doesn't -- or, it does, but the assertions are not run.

I can dig deeper into this, just creating an issue first to start a discussion.

**Comment by caioaao** [comment]
Hi, thanks for reporting! Can you post a small project that reproduces this so I can investigate it?

**Comment by orestis** [comment]
For sure! I’ll start with a clean slate and make a clean repro. Could be that I’m just thick :)

25 Απρ 2019, 12:57 πμ, ο χρήστης «Caio Oliveira <notifications@github.com>» έγραψε:
